services:
  - type: web
    name: skill-swap-django-api
    runtime: python
    rootDir: django_backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn skill_swap.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: skill_swap
      - key: JWT_SECRET
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ZEGO_APP_ID
        sync: false
      - key: ZEGO_SERVER_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false

  - type: web
    name: skill-swap-socket-service
    runtime: node
    rootDir: socket_service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: DJANGO_API_URL
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
