from django.urls import path
from .views import AuditEventView, ProtectedMediaView, AdminActivityView, AdminCollectionView, AdminDashboardView, AssessmentStartView, AssessmentSubmitView, AvatarUploadView, BlockView, CertificateIssueView, CertificateListView, CertificateVerifyView, ConversationAccessView, ConversationMessageView, ForgotPasswordView, LoginView, LogoutView, MatchDiscoverView, MatchRequestActionView, MatchRequestView, MeView, NotificationView, ProfileView, RegisterView, ReportView, ResetPasswordView, ResendOtpView, SessionActionView, SessionView, SessionVideoTokenView, UserSkillsView, VerifyOtpView

urlpatterns = [
    path("auth/register", RegisterView.as_view()),
    path("auth/verify-otp", VerifyOtpView.as_view()),
    path("auth/resend-otp", ResendOtpView.as_view()),
    path("auth/login", LoginView.as_view()),
    path("auth/forgot-password", ForgotPasswordView.as_view()),
    path("auth/reset-password", ResetPasswordView.as_view()),
    path("auth/logout", LogoutView.as_view()),
    path("auth/me", MeView.as_view()),
    path("profile/me", ProfileView.as_view()),
    path("profile/avatar", AvatarUploadView.as_view()),
    path("my-skills", UserSkillsView.as_view()),
    path("matches/requests", MatchRequestView.as_view()),
    path("matches/requests/<str:request_id>", MatchRequestActionView.as_view()),
    path("blocks", BlockView.as_view()),
    path("sessions", SessionView.as_view()),
    path("reports", ReportView.as_view()),
    path("notifications", NotificationView.as_view()),
    path("notifications/<str:notification_id>", NotificationView.as_view()),
    path("certificates", CertificateListView.as_view()),
    path("sessions/<str:session_id>/certificate", CertificateIssueView.as_view()),
    path("assessments/start", AssessmentStartView.as_view()),
    path("assessments/<str:attempt_id>/submit", AssessmentSubmitView.as_view()),
    path("matches/discover", MatchDiscoverView.as_view()),
    path("conversations/<str:conversation_id>/access", ConversationAccessView.as_view()),
    path("conversations/<str:conversation_id>/messages", ConversationMessageView.as_view()),
    path("sessions/<str:session_id>/video-token", SessionVideoTokenView.as_view()),
    path("sessions/<str:session_id>/<str:action>", SessionActionView.as_view()),
    path("certificates/verify/<str:token>", CertificateVerifyView.as_view()),
    path("admin/dashboard", AdminDashboardView.as_view()),
    path("admin/activity", AdminActivityView.as_view()),
    path("admin/<str:collection>", AdminCollectionView.as_view()),
    path("admin/<str:collection>/<str:record_id>", AdminCollectionView.as_view()),
    path("audit-events", AuditEventView.as_view()),
    path("media/<str:media_type>/<str:record_id>", ProtectedMediaView.as_view()),
]
